import json
from utils import get_openrouter_client

def summarize_resume(resume_text: str) -> dict:
    """
    Summarize a resume using OpenRouter's LLM API.
    
    Args:
        resume_text: The resume text in markdown format
        
    Returns:
        dict: Contains 'summary' and optionally 'reasoning' if available
    """
    client = get_openrouter_client()
    
    # API call with reasoning
    response = client.chat.completions.create(
        model="nvidia/nemotron-3-nano-30b-a3b:free",
        messages=[
            {
                "role": "user",
                "content": f"Provide a comprehensive summary of the following resume. Include key skills, experience, education, and notable achievements:\n\n{resume_text}"
            }
        ],
        extra_body={"reasoning": {"enabled": True}}
    )
    
    # Extract the assistant message with reasoning_details
    message = response.choices[0].message
    
    result = {
        "summary": message.content
    }
    
    # Add reasoning if available
    if hasattr(message, 'reasoning_content') and message.reasoning_content:
        result["reasoning"] = message.reasoning_content
    
    return result


def generate_job_projects(resume_text: str, job_description: str) -> dict:
    """
    Analyze resume and job description to generate 5 hands-on project recommendations.
    
    Args:
        resume_text: The resume text in markdown format
        job_description: The job description text
        
    Returns:
        dict: Contains 'analysis_summary' and 'projects' list with 5 project recommendations
    """
    client = get_openrouter_client()
    
    prompt = f"""Analyze the following resume and job description to identify skill gaps and growth areas.
Generate 5 hands-on projects that will help this candidate prepare for the role.

RESUME:
{resume_text}

JOB DESCRIPTION:
{job_description}

Please provide:
1. A brief analysis summary (2-3 sentences) identifying key gaps and opportunities
2. 5 practical hands-on projects tailored to bridge these gaps

For each project, include:
- Title: Clear, specific project name
- Description: 2-3 sentences explaining what the project does and why it's relevant
- Main Steps: 3-5 concrete, actionable steps to complete the project
- Skills Learned: Key skills that directly map to the job requirements

Format your response as a JSON object with this structure:
{{
    "analysis_summary": "Brief gap analysis between resume and job requirements",
    "projects": [
        {{
            "title": "Project name",
            "description": "What the project does and why it matters",
            "steps": ["Step 1", "Step 2", "Step 3", "Step 4", "Step 5"],
            "skills": ["Skill 1", "Skill 2", "Skill 3"]
        }}
    ]
}}

Return ONLY the JSON object, no additional text."""
    
    response = client.chat.completions.create(
        model="nvidia/nemotron-3-nano-30b-a3b:free",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.7
    )
    
    # Extract the response content
    content = response.choices[0].message.content
    
    # Try to parse JSON from the response
    try:
        # Sometimes the model wraps JSON in markdown code blocks
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].split("```")[0].strip()
        
        result = json.loads(content)
        
        # Validate the structure
        if "analysis_summary" not in result or "projects" not in result:
            raise ValueError("Invalid response structure")
        
        if len(result["projects"]) < 5:
            raise ValueError(f"Expected 5 projects, got {len(result['projects'])}")
        
        return result
        
    except (json.JSONDecodeError, ValueError) as e:
        # If JSON parsing fails, return a fallback structure
        return {
            "analysis_summary": "Analysis completed. Here are your project recommendations.",
            "projects": [
                {
                    "title": f"Project {i+1}",
                    "description": "Project details generated by AI",
                    "steps": ["Step 1", "Step 2", "Step 3"],
                    "skills": ["Relevant skills"]
                }
                for i in range(5)
            ],
            "raw_response": content
        }